<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractmocktestclass' => '/_files/AbstractMockTestClass.php',
                'abstracttrait' => '/_files/AbstractTrait.php',
                'aninterface' => '/_files/AnInterface.php',
                'anotherinterface' => '/_files/AnotherInterface.php',
                'bar' => '/_files/Bar.php',
                'classthatimplementsserializable' => '/_files/ClassThatImplementsSerializable.php',
                'classwithstaticmethod' => '/_files/ClassWithStaticMethod.php',
                'foo' => '/_files/Foo.php',
                'framework_mockbuildertest' => '/MockBuilderTest.php',
                'framework_mockobject_generatortest' => '/GeneratorTest.php',
                'framework_mockobject_invocation_objecttest' => '/MockObject/Invocation/ObjectTest.php',
                'framework_mockobject_invocation_statictest' => '/MockObject/Invocation/StaticTest.php',
                'framework_mockobjecttest' => '/MockObjectTest.php',
                'framework_proxyobjecttest' => '/ProxyObjectTest.php',
                'interfacewithstaticmethod' => '/_files/InterfaceWithStaticMethod.php',
                'methodcallback' => '/_files/MethodCallback.php',
                'methodcallbackbyreference' => '/_files/MethodCallbackByReference.php',
                'mockable' => '/_files/Mockable.php',
                'partialmocktestclass' => '/_files/PartialMockTestClass.php',
                'someclass' => '/_files/SomeClass.php',
                'staticmocktestclass' => '/_files/StaticMockTestClass.php',
                'traversablemocktestinterface' => '/_files/TraversableMockTestInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
