<?php
require_once 'PHPUnit/Framework.php';{requireClassFile}

/**
 * Test class for {className}.
 * Generated by PHPUnit on {date} at {time}.
 */
class {className}Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var    {className}
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new {className};
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }
{methods}}
?>
