<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://some-web-service.com/CustomUI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsdLocal0="http://www.some-web-service.com/xml/ContactInformation" targetNamespace="http://some-web-service.com/CustomUI">
    <message name="Contact_Information_Input">
        <part name="Contact_Id" type="xsd:string" />
    </message>
    <message name="Contact_Information_Output">
        <part name="Response_Code" type="xsd:string" />
        <part name="Response_Message" type="xsd:string" />
    </message>
    <portType name="Contact_Information">
        <operation name="Contact_Information">
            <input message="tns:Contact_Information_Input" />
            <output message="tns:Contact_Information_Output" />
        </operation>
    </portType>
    <binding name="Contact_Information" type="tns:Contact_Information">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc" />
        <operation name="Contact_Information">
            <soap:operation soapAction="rpc/http://some-web-service.com/CustomUI:Contact_Information" />
            <input>
                <soap:body namespace="http://some-web-service.com/CustomUI" use="literal" />
            </input>
            <output>
                <soap:body namespace="http://some-web-service.com/CustomUI" use="literal" />
            </output>
        </operation>
    </binding>
    <service name="Web_Service">
        <port binding="tns:Contact_Information" name="Contact_Information">
            <soap:address location="https://some-web-service.com" />
        </port>
    </service>
</definitions>
